### ISSUE TITLE
Component Tests

### ISSUE THREAD

**Issue by aamay001** [aamay001/react-resume#36] opened 2019-07-12 18:51 UTC
Write tests.

**Comment by JaiParakh** [comment] 2019-10-18 17:31
Can you please explain the issue in detail.

**Comment by aamay001** [comment] 2019-10-18 17:37
> Can you please explain the issue in detail.

You can add any test that you'd like to add for Components (i.e. rendering tests, etc.) Use Jest.

**Comment by paulywill** [comment] 2019-10-19 17:57
@aamay001 I’m going to take this on.

**Comment by paulywill** [comment] 2019-10-21 16:13
@aamay001 How does one run the: VisibilityChanger.test.js ?

**Comment by aamay001** [comment] 2019-10-22 01:41
> @aamay001 ~How does one run the: VisibilityChanger.test.js ?~
> 
> Still learning learning the difference between tests.

just for reference, it's `npm run test`

**Comment by paulywill** [comment] 2019-10-22 21:37
@aamay001 @oriane212 @tsargent 

Working away on[ CodeEditor test ](https://github.com/paulywill/react-resume/commit/c91b8d4e0d876a51b60dc2248fbe1622848eb6bd) and having the troubles with determining if the text 'Code Editor' is between the DIV tags.

I've put two links on my commit I'll have to read some more later.

Any ideas what I'm doing wrong?

**Comment by aamay001** [comment] 2019-10-22 22:50
You're going one child too deep. It should just be:
`expect(menu.firstChild.textContent).toBe('Code Editor');` 

@paulywill

**Comment by paulywill** [comment] 2019-10-23 17:22
@aamay001 Another similar [question](https://github.com/paulywill/react-resume/commit/13810bf4c7258fba97dc5a7d8cb3e693292557c0).

**Comment by paulywill** [comment] 2020-01-24 17:10
@aamay001 Found some extra cycles, trying to complete full coverage for CodeEditor component.

If you have a change check out my [branch](https://github.com/paulywill/react-resume/commit/9944e1db9e38a48d19305e613d24b73db0f004b3).

Some of the warning messages I was getting when testing for Brace was resolved by updating [React-Ace](https://www.npmjs.com/package/react-ace):

> NOTE FOR VERSION 8! : We have stopped support for Brace and now use Ace-builds. Please read the documentation on how to migrate. Examples are being updated.

Because I had to introduce Ace-build there's a new warning when running my CodeEditor.test.js:

`  Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver`

Not sure the ideal place I have to put the ace.config.set('basePath', 'path')  in the React app.

I've tested locally the app and there appears to be no visible regression.

**Comment by paulywill** [comment] 2020-01-24 21:06
@aamay001 Is there any interest in us creating snapshots?

I'm just learning that it's tricky if not [shallow](https://www.robinwieruch.de/jest-snapshot-shallow-render)?

**Comment by aamay001** [comment] 2020-01-27 16:01
Hi Paul,

If you're up for it, that's okay with me. Personally, I have not used
snapshots, although, I have read about them. If you see a need to using
them, go ahead and submit a PR that includes them and I'll make sure to
review.

Thanks,

Andy

**Comment by paulywill** [comment] 2020-01-27 21:32
@aamay001 Resolved the snapshot for the CodeEditor.

Having a gotcha with testing `componentDidUpdate` to get full code coverage.

Every example I've looked at suggested shallow mounting using Enzyme.

The react-ace is also adding some complexity, trying to refer some tests from that project.

**Comment by aamay001** [comment] 2020-10-03 14:14
New Issues being added for testing with Crypress.

**Closed** 2020-10-03 14:14 UTC
Labels: enhancement, hacktoberfest, help wanted
